default: &default
  adapter: postgresql
  encoding: unicode
  username: okan
  password: 121212
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: apalapucia_development

test:
  <<: *default
  database: apalapucia_test

production:
  <<: *default
  database: apalapucia_production
  username: apalapucia
  password: <%= ENV['APALAPUCIA_DATABASE_PASSWORD'] %>
